version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - mfilip
  assignees:
  - mfilip
  ignore:
  - dependency-name: typescript
    versions:
    - 4.2.2
  - dependency-name: semantic-release
    versions:
    - 17.4.0
  registries:
  - npm-registry-registry-npmjs-org
